[package]
name = "hotshot-events-service"
version = "0.1.57"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-broadcast = "0.7"
async-lock = "2.8"
async-trait = "0.1"
clap = { version = "4.4", features = ["derive", "env"] }
derivative = "2.2"
derive_more = "0.99"
either = { version = "1.12", features = ["serde"] }
futures = "0.3"
hotshot-types = { git = "https://github.com/EspressoSystems/HotShot.git", branch = "bump/0.5.83" }
libp2p-identity = { version = "0.2", features = ["serde"] }
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
snafu = "0.8"
tagged-base64 = "0.4"
tide-disco = "0.9"
tokio = { version = "1.41", features = ["macros"] }
toml = "0.8"
tracing = "0.1"
tracing-test = "0.2"
vbs = "0.1.4"

[dev-dependencies]
hotshot-example-types = { git = "https://github.com/EspressoSystems/HotShot.git", branch = "bump/0.5.83" }
portpicker = "0.1.1"
surf-disco = "0.9"
