[package]
name = "hotshot-events-service"
version = "0.1.38"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-broadcast = "0.7"
async-compatibility-layer = { version = "1.1", default-features = false, features = [
    "logging-utils",
] }
async-lock = "2.8"
async-std = { version = "1", features = ["attributes"] }
async-trait = "0.1"
clap = { version = "4.4", features = ["derive", "env"] }
derivative = "2.2"
derive_more = "0.99"
either = { version = "1.12", features = ["serde"] }
futures = "0.3"
hotshot-types = { git = "https://github.com/EspressoSystems/HotShot.git", branch = "bump/rc-0.5.72" }
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
snafu = "0.8"
tagged-base64 = "0.4"
tide-disco = "0.9"
toml = "0.8"
tracing = "0.1"
vbs = "0.1.4"

[dev-dependencies]
hotshot-example-types = { git = "https://github.com/EspressoSystems/HotShot.git", branch = "bump/rc-0.5.72" }
portpicker = "0.1.1"
surf-disco = "0.9"
