[package]
name = "hotshot-events-service"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-compatibility-layer = { version = "1.1", default-features = false, features = [
    "logging-utils",
] }
async-broadcast = "0.7"
async-std = { version = "1", features = ["attributes"] }
async-lock = "2"
async-trait = "0.1"
clap = { version = "4.4", features = ["derive", "env"] }
derive_more = "0.99"
derivative = "2.2"
either = { version = "1.10", features = ["serde"] }
futures = "0.3"
hotshot-types = { git = "https://github.com/EspressoSystems/HotShot.git", branch = "hg/include_builder_keys" }
serde = { version = "1.0", features = ["derive"] }
snafu = "0.8"
tagged-base64 = { git = "https://github.com/EspressoSystems/tagged-base64", tag = "0.3.4" }
tide-disco = { git = "https://github.com/EspressoSystems/tide-disco.git", tag = "v0.5.0" }
toml = "0.8"
tracing = "0.1"
versioned-binary-serialization = { git = "https://github.com/EspressoSystems/versioned-binary-serialization", tag = "0.1.2" }

[dev-dependencies]
hotshot-example-types = { git = "https://github.com/EspressoSystems/HotShot.git", branch = "hg/include_builder_keys" }
portpicker = "0.1.1"
surf-disco = { git = "https://github.com/EspressoSystems/surf-disco.git", tag = "v0.5.0" }
